<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <OutputPath>bin\</OutputPath>
    <OutDir>bin\</OutDir>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Demo.Contracts\Demo.Contracts.csproj" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.ServiceModel.Activation" />
    <Reference Include="System.IdentityModel" />
    <Reference Include="System.Web" />
    <Reference Include="System.Configuration" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Demo.svc" CopyToOutputDirectory="Never" />
    <None Include="health.aspx" CopyToOutputDirectory="Never" />
    <None Include="Web.config" CopyToOutputDirectory="Never" />
  </ItemGroup>
</Project>
